chat:
  caps-allowed: 0.3
  caps-ignore-length: 4
colours:
  PenguinJ2: "AQUA"
  MrSugarCaney: "GREEN"
teams:
  example_team:
    members:
    - example_member_1
    - example_member_2
    color: "GREEN"
    accent: ""
  example_team_2:
    members:
    - example_member_3
    - example_member_4
    color: "GOLD"
    accent: "ITALIC"